### ISSUE TITLE
Issues with the molnet function

### ISSUE THREAD

**Issue by Pacifisten** [hpetren/chemodiv#1]
The function molnet requires choosing as compDisMat the underlying object $fingerDisMat if not it doesn't work

and molnetplot requires selecting in networkObject the underlying object $networkObject

**Comment by hpetren** [comment]
For `molNet` this is intentional since the output of `compDis` is a list that can contain more than one matrix. The user then has to specify which matrix to use as input. For `molNetPlot`, input was structured to be similar as for `molNet` for consistency. Input format is explained in the function documentation for `molNetPlot`, but less so for `molNet`. I will update this to be more clear.

I could modify functions to also accept the whole lists as input, in cases where that is suitable. Is there a need for this (e.g. use cases when the current design of the input/output of functions causes problems)?

**Comment by Pacifisten** [comment]
Sorry was on paternal leave, back to code :). 

I think if the input is the one generated from the previous method it make sense that it should not be specified for a single item generated from the previous step.

Will try the new version on a very large set of molecules! Keep up the good work!
